"""
TRITON M47 — Perimeter Streaming Engine

Single-threaded event-driven engine. Per-message hot path:

    parse → spatial index lookup → point-in-polygon → state update
          → rule pipeline → alert dispatch

Designed for sub-millisecond P50 detection latency on commodity hardware.
Latency is measured end-to-end per message with perf_counter_ns and rolled
up into P50 / P95 / P99 percentiles.

This is deliberately scoped to streaming intrusion / perimeter detection.
It does NOT make GO/NO-GO decisions — those are M26 AIP's job. M47 emits
typed events that AIP consumes asynchronously through the alert bus.
"""
from __future__ import annotations

import time
import math
import bisect
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Set, Tuple
from collections import deque

from shapely.geometry import Point
from shapely.strtree import STRtree

from geofences import Geofence, all_fences


# ============================================================
# DATA TYPES
# ============================================================

@dataclass
class AISMessage:
    """Decoded AIS position report (Type 1/2/3 equivalent)."""
    mmsi: int                # Maritime Mobile Service Identity
    timestamp: float         # epoch seconds
    lat: float
    lon: float
    sog: float               # speed over ground, knots
    cog: float               # course over ground, degrees
    nav_status: int = 0      # 0=under way using engine, 1=at anchor, etc.
    vessel_class: str = "cargo"   # cargo, tanker, fishing, naval, unknown
    name: str = ""           # vessel name (may be spoofed)


@dataclass
class VesselState:
    mmsi: int
    last_msg: Optional[AISMessage] = None
    last_seen: float = 0.0
    inside_fences: Set[str] = field(default_factory=set)
    last_position: Optional[Tuple[float, float]] = None  # (lon, lat)
    last_sog: float = 0.0
    msg_count: int = 0
    name_history: List[str] = field(default_factory=list)
    low_speed_since: Optional[float] = None  # for loitering detection


@dataclass
class Alert:
    alert_type: str          # GEOFENCE_ENTRY, SPEED_ANOMALY, AIS_DROPOUT, ...
    severity: int            # 1..5
    timestamp: float
    mmsi: int
    fence_id: Optional[str]
    detail: str
    detection_latency_us: float = 0.0


# ============================================================
# THE ENGINE
# ============================================================

class PerimeterEngine:
    """
    Streaming perimeter and intrusion detection engine.

    Wire-up:
        engine = PerimeterEngine(fences=all_fences())
        engine.on_alert(my_handler)
        for msg in ais_stream:
            engine.ingest(msg)

    Rule severity mapping (so consumers can filter the bus):
        1  informational     vessel observed near fence
        2  notable           TSS lane usage, normal
        3  caution           shadow zone, AIS dropout starting
        4  warning           chokepoint entry, exclusion zone breach
        5  critical          IRGC zone entry, CSG bubble breach, going dark
    """

    # Tunable thresholds — calibrated for Persian Gulf traffic
    LOITERING_SOG_KN = 0.5
    LOITERING_DURATION_S = 600    # 10 min stationary in a fenced zone
    CARGO_OVERSPEED_KN = 25.0
    DROPOUT_THRESHOLD_S = 120     # silence > 2 min in a critical fence
    CPA_HORIZON_S = 300           # look 5 min ahead for closing approaches
    CPA_THRESHOLD_NM = 0.5

    def __init__(self, fences: List[Geofence]):
        self.fences: List[Geofence] = fences
        self.fence_by_id: Dict[str, Geofence] = {f.fence_id: f for f in fences}
        # STRtree expects geometries; we keep a parallel id list for lookup
        self._geoms = [f.polygon for f in fences]
        self._tree = STRtree(self._geoms)

        self.vessels: Dict[int, VesselState] = {}
        self.alerts_emitted: int = 0
        self._handlers: List[Callable[[Alert], None]] = []

        # Latency telemetry (nanoseconds)
        self._latencies_ns: List[int] = []
        self._max_latency_samples = 1_000_000

        # Tick scheduler — for time-based sweeps (going dark)
        self._messages_since_sweep = 0
        self._sweep_interval_messages = 500

    # --- subscriber API ---------------------------------------------------

    def on_alert(self, handler: Callable[[Alert], None]) -> None:
        self._handlers.append(handler)

    def _emit(self, alert: Alert) -> None:
        self.alerts_emitted += 1
        for h in self._handlers:
            h(alert)

    # --- hot path ---------------------------------------------------------

    def ingest(self, msg: AISMessage) -> List[Alert]:
        """Process one AIS message. Returns alerts generated by this message."""
        t0 = time.perf_counter_ns()
        alerts: List[Alert] = []

        # 1. Get or create vessel state
        vs = self.vessels.get(msg.mmsi)
        if vs is None:
            vs = VesselState(mmsi=msg.mmsi)
            self.vessels[msg.mmsi] = vs

        # 2. Spatial index query — STRtree returns indices of candidate geoms
        point = Point(msg.lon, msg.lat)
        candidate_idx = self._tree.query(point)
        new_inside: Set[str] = set()
        for idx in candidate_idx:
            fence = self.fences[idx]
            if fence.polygon.contains(point):
                new_inside.add(fence.fence_id)

        # 3. Detect entries and exits
        prev_inside = vs.inside_fences
        entered = new_inside - prev_inside
        exited = prev_inside - new_inside

        for fid in entered:
            f = self.fence_by_id[fid]
            alerts.append(Alert(
                alert_type="GEOFENCE_ENTRY",
                severity=f.severity,
                timestamp=msg.timestamp,
                mmsi=msg.mmsi,
                fence_id=fid,
                detail=f"{msg.name or msg.mmsi} entered {f.name}",
            ))

        for fid in exited:
            f = self.fence_by_id[fid]
            alerts.append(Alert(
                alert_type="GEOFENCE_EXIT",
                severity=max(1, f.severity - 2),
                timestamp=msg.timestamp,
                mmsi=msg.mmsi,
                fence_id=fid,
                detail=f"{msg.name or msg.mmsi} exited {f.name}",
            ))

        # 4. Speed anomaly (only meaningful if we have history)
        if vs.last_msg is not None:
            if msg.vessel_class in ("cargo", "tanker") and msg.sog > self.CARGO_OVERSPEED_KN:
                alerts.append(Alert(
                    alert_type="SPEED_ANOMALY",
                    severity=3,
                    timestamp=msg.timestamp,
                    mmsi=msg.mmsi,
                    fence_id=None,
                    detail=f"{msg.vessel_class} at {msg.sog:.1f}kn (>{self.CARGO_OVERSPEED_KN}kn)",
                ))

        # 5. Loitering inside a fenced zone
        in_critical = bool(new_inside & {fid for fid, f in self.fence_by_id.items()
                                         if f.severity >= 4})
        if in_critical and msg.sog < self.LOITERING_SOG_KN:
            if vs.low_speed_since is None:
                vs.low_speed_since = msg.timestamp
            elif msg.timestamp - vs.low_speed_since > self.LOITERING_DURATION_S:
                alerts.append(Alert(
                    alert_type="LOITERING",
                    severity=4,
                    timestamp=msg.timestamp,
                    mmsi=msg.mmsi,
                    fence_id=next(iter(new_inside)) if new_inside else None,
                    detail=f"{msg.name or msg.mmsi} stationary "
                           f"{msg.timestamp - vs.low_speed_since:.0f}s in critical zone",
                ))
                vs.low_speed_since = msg.timestamp  # reset to avoid spam
        else:
            vs.low_speed_since = None

        # 6. Identity flip detection (MMSI is fixed but name can be changed)
        if msg.name and (not vs.name_history or vs.name_history[-1] != msg.name):
            if vs.name_history:
                alerts.append(Alert(
                    alert_type="IDENTITY_FLIP",
                    severity=4,
                    timestamp=msg.timestamp,
                    mmsi=msg.mmsi,
                    fence_id=None,
                    detail=f"MMSI {msg.mmsi} name changed "
                           f"'{vs.name_history[-1]}' → '{msg.name}'",
                ))
            vs.name_history.append(msg.name)
            if len(vs.name_history) > 5:
                vs.name_history = vs.name_history[-5:]

        # 7. Update state
        vs.last_msg = msg
        vs.last_seen = msg.timestamp
        vs.last_position = (msg.lon, msg.lat)
        vs.last_sog = msg.sog
        vs.inside_fences = new_inside
        vs.msg_count += 1

        # 8. Periodic time-based sweep (going dark, dropout)
        self._messages_since_sweep += 1
        if self._messages_since_sweep >= self._sweep_interval_messages:
            self._messages_since_sweep = 0
            sweep_alerts = self._sweep(now=msg.timestamp)
            alerts.extend(sweep_alerts)

        # 9. Latency sample
        latency_ns = time.perf_counter_ns() - t0
        if len(self._latencies_ns) < self._max_latency_samples:
            self._latencies_ns.append(latency_ns)

        # 10. Stamp and dispatch
        for a in alerts:
            a.detection_latency_us = latency_ns / 1000.0
            self._emit(a)

        return alerts

    # --- time-based sweep ------------------------------------------------

    def _sweep(self, now: float) -> List[Alert]:
        """Detect going-dark vessels. Only sweeps tracks in critical fences."""
        alerts: List[Alert] = []
        critical_fences = {fid for fid, f in self.fence_by_id.items() if f.severity >= 4}

        for vs in self.vessels.values():
            if not vs.inside_fences & critical_fences:
                continue
            silence = now - vs.last_seen
            if silence > self.DROPOUT_THRESHOLD_S:
                fid = next(iter(vs.inside_fences & critical_fences))
                alerts.append(Alert(
                    alert_type="AIS_GOING_DARK",
                    severity=5,
                    timestamp=now,
                    mmsi=vs.mmsi,
                    fence_id=fid,
                    detail=f"MMSI {vs.mmsi} silent {silence:.0f}s inside {fid}",
                ))
        return alerts

    # --- telemetry --------------------------------------------------------

    def latency_percentiles(self) -> Dict[str, float]:
        """Return P50/P95/P99/max latency in microseconds."""
        if not self._latencies_ns:
            return {"p50_us": 0.0, "p95_us": 0.0, "p99_us": 0.0, "max_us": 0.0}
        sorted_ns = sorted(self._latencies_ns)
        n = len(sorted_ns)
        def pct(p):
            idx = min(n - 1, int(p * n))
            return sorted_ns[idx] / 1000.0
        return {
            "samples": n,
            "p50_us": pct(0.50),
            "p95_us": pct(0.95),
            "p99_us": pct(0.99),
            "p999_us": pct(0.999),
            "max_us": sorted_ns[-1] / 1000.0,
            "mean_us": (sum(sorted_ns) / n) / 1000.0,
        }

    def reset_latency_telemetry(self) -> None:
        self._latencies_ns.clear()


# ============================================================
# CLI smoke test
# ============================================================
if __name__ == "__main__":
    fences = all_fences()
    engine = PerimeterEngine(fences=fences)

    captured = []
    engine.on_alert(lambda a: captured.append(a))

    # Synthesize a tanker transiting Hormuz from east to west
    base_t = time.time()
    track = [
        (57.30, 26.20, "Strait approach east"),
        (57.00, 26.40, "Approaching Hormuz choke"),
        (56.70, 26.65, "Inside choke"),
        (56.40, 26.80, "Exiting choke west"),
        (56.10, 26.90, "Past Larak"),
        (55.80, 27.00, "Free water"),
    ]
    for i, (lon, lat, label) in enumerate(track):
        msg = AISMessage(
            mmsi=636017123, timestamp=base_t + i * 60,
            lat=lat, lon=lon, sog=14.5, cog=270,
            vessel_class="tanker", name="MT EXAMPLE",
        )
        alerts = engine.ingest(msg)
        print(f"[{label:30s}] generated {len(alerts)} alert(s)")
        for a in alerts:
            print(f"   → [{a.severity}] {a.alert_type:18s} {a.detail}  ({a.detection_latency_us:.1f}µs)")

    print(f"\nTotal alerts: {engine.alerts_emitted}")
    print(f"Latency: {engine.latency_percentiles()}")
